### ISSUE TITLE
B_GITHUBVER no longer is able to determine the date of the last commit

### ISSUE THREAD

**Issue by Thulium-Drake** [mverboom/build#5]
It seems that any recipe that contains B_GITHUBVER no longer is able to complete the version check. I've tested it with multiple Github repositories to rule out any odd things with a specific repo. Using the example build.recipe, only changing B_GITVER with B_GITHUBVER:

```
build -c build-test
Version command for build-test returned no output.
```

From what I have been able to gather the output when running the check manually has an error processing a date. But it still prints the last date. in the second line.

```
wget -q -O - https://github.com/mverboom/build | sed '/datetime=/!d; s/.*time-ago datetime="[TZ\:0-9\-]*">\([^<]*\)<.*/\1/' | while read line; do date --date="$line" "+%Y%m%d"; done | sort | tail -1
date: invalid date ‘<span itemprop="dateModified"><relative-time datetime="2018-06-10T08:17:11Z">Jun 10, 2018</relative-time></span>’
20180610
```

I have tried fixing this by redirecting the errors from date to /dev/null, but that doesn't seem to fix the issue.

**Comment by mverboom** [comment]
Fixed in 0.52
